version: "2"
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    network_mode: bridge
    hostname: redis
    expose:
      - 6379
    ports:
      - 6379:6379
    restart: unless-stopped
  # APP*****************************************
  apigateway:
    image: apigateway:latest
    network_mode: bridge
    container_name: apigateway
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - redis
    links:
      - redis